### ISSUE TITLE
Dam or plant location ?

### ISSUE THREAD

**Issue by laure2019** [energy-modelling-toolkit/hydro-power-database#14]
Hi and thank you for your great work!

The coordinates in the database sometimes refer to the dam (e.g. the coordinates of H47 refer to the Roselend dam and not to the Bathie power plant) and sometimes to the power plant (e.g. the coordinates of H554 refer to the Portillon power plant and not to the dam on which it depends) 
I imagine that these differences depend on the sources used. But maybe there is a way to know what the coordinates indicated for the power station correspond to? I would be happy to know more.

And same for dam height / head, is it possible to know which of the two data recorded in 'dam_height' corresponds?

Thanks in advance

**Comment by matteodefelice** [comment]
unfortunately it's hard to say, I have merged different datasets and sometimes this wasn't specified. In general, whenever possible, we report the dam head (the number we actually use for power system modelling) but - again - sometimes that was not reported and we could only go for the dam height.
