### ISSUE TITLE
Fields occasionally misaligned.

### ISSUE THREAD

**Issue by kristvanbesien** [energy-modelling-toolkit/hydro-power-database#18]
Trying to load this in to Excell I noticed that quite a few rows (82,120,213) have extra comma's in or after the name field.

Eg:

`H1235,Nové mesto Nove Mesto n,V, Hydroelectric Power Plant Slovakia - Nove Mesto n,V, Hydroelectric Power Plant Slovakia,25.7,,HROR,SK,48.77245,17.85146,,,,,1823,42655,
`

Here there are four extra commas in the plant name. This breaks import of this file in a spreadsheet or database.

**Comment by matteodefelice** [comment]
I removed all the commas in the plant names, now it should work.
