### ISSUE TITLE
Add ENTSOE EIC production codes

### ISSUE THREAD

**Issue by flacombe** [energy-modelling-toolkit/hydro-power-database#2]
Hi and thank you for the incredible gathering work done to create this database.

It would be great to add existing EIC codes corresponding to each plant (W-codes)
https://www.entsoe.eu/data/energy-identification-codes-eic/
Such codes are assigned by local codification offices, mainly TSOs (which list can be found on ENTSOE website). This is valuable for all kind of power plants, not only hydroelectric ones.

OpenStreetMap is doing such collection currently.
https://wiki.openstreetmap.org/wiki/Key:ref:EU:ENTSOE_EIC#Power_generators_or_consumers_:_W-codes

Such a code ease a lot conflation tasks by using a consistent and unique codes on the whole perimeter covered by this database.

All the best

**Comment by matteodefelice** [comment]
In principle, I have started with a list of power plants  that are part of our internal power-plant database which includes also the EIC codes (and this database will be released openly soon by the way). But then I have decided to not include this information into this database for two reasons: 1. in many cases I am aggregating the units (with some difficulties as you mentioned [here](https://github.com/energy-modelling-toolkit/hydro-power-database/issues/3)) and 2. in many cases it is impossible to find the correct EIC codes. However, I agree with you that the EIC codes would be a very valuable addition to this database.

**Comment by flacombe** [comment]
Understood, thank you

> 1. in many cases I am aggregating the units (with some difficulties as you mentioned here)

Is this because you only have units and not actual plant involving those units, right?

**Comment by matteodefelice** [comment]
Well, my sources are very heterogeneous and in many cases I could only find information and data regarding the whole plants, in other cases instead I could find more detailed numbers. Then, giving the scope of the dataset, I preferred to aggregate to create a more manageable (IMHO) dataset.

**Comment by flacombe** [comment]
Hello

This issue was closed as completed, but I can't find any related column in the latest release of the dataset.
Was it a duplicate or something?

**Comment by matteodefelice** [comment]
Unfortunately, I am not including EIC in the dataset because finding this information is too time-consuming. If you need EICs, you can try using the JRC Power Plant Database available here: https://energy-industry-geolab.jrc.ec.europa.eu/ (we are working on a new release).

**Comment by flacombe** [comment]
No problem to find official EIC.
The goal was to make this database available to processes that use EIC as pivot key.

Currently, is there any id or key I can use to join your database to other datasets?

**Comment by flacombe** [comment]
Thank you for the table, it will be really useful.

I'd recommend to add it as csv in the repository, despite incomplete. It can encourage people to help you afterwards.
