### ISSUE TITLE
Names including generation unit references

### ISSUE THREAD

**Issue by flacombe** [energy-modelling-toolkit/hydro-power-database#3]
I've noticed that some plants' names seems to contain references to individual generators.

Like H24 => Bissorte Hydroelectric 1/2/3

Actually, it can refer to 2 different point of view for the same infrastructure :
* Is this Bissorte plants 1, 2 and 3?
Bissorte 1 (75 MW) : https://www.openstreetmap.org/relation/7759495
Bissorte 2 & 3 (Pumping + Pelton 748 MW) : https://www.openstreetmap.org/relation/2865507

* Or generating units 1, 2 and 3 inside super bissorte power plant (out of 5 generation units)?
https://www.openstreetmap.org/relation/2865507

There is also H31 - Super bissorte SUPER BISSORTE 1 - Super-Bissorte Pumped Storage Hydroelectric Power Station France
With 742.3 MW, it should definitely be included in H24

If you're interested in tackling cleaning challenges, you can get useful data from OSM
Solving #2 will help to directly link your records to existing features there

All the best

**Comment by matteodefelice** [comment]
Thanks for this, it's really helpful. 
The item H24 is based on this http://globalenergyobservatory.org/geoid/39783 but I have always struggled a bit on Bissorte and Super-Bissorte (which is also present here http://globalenergyobservatory.org/geoid/44379 ). The OSM links are very useful but you pasted the same one twice, is it correct? I will propose a fix asap. 

(is it possible to explore on OSM only the power-plants? )

**Comment by flacombe** [comment]
You're welcome and it's nice to see it's useful

"Bissorte" location is a nice place to challenge precision of databases
You've got 2 different plants with approximately the same name and another one (Orelle)

Here you go for the full picture : https://openinframap.org/#14.56/45.20403/6.57676

Global Energy Observatory is a bit wrong with figures, maybe because the site is complex to understand from outside. OSM (or other crowdsourcing platform) provides local data to complete any other global repository.

> The OSM links are very useful but you pasted the same one twice, is it correct?

Yes it was intended to provide 2 different ways to see the same infrastructure

You can query OSM with Overpass-turbo tool, with appropriate request you get power plants like this (for instance in France):
http://overpass-turbo.eu/s/IJv
This is a work in progress and data should be taken carefully
Documentation : https://wiki.openstreetmap.org/wiki/Tag:power%3Dplant

**Comment by matteodefelice** [comment]
Ok, I have removed the H31 and updated the H24, for sake of simplicity I have classified the entire Bissorte (1/2/3) as pumping. I will release a new version soon with other changes that were in the pipeline. Thank you again also for showing me some useful tools (overpass-turbo, openinframap, etc.).

**Comment by flacombe** [comment]
Ok it sounds good to merge H24 and H31 regarding output rates

I don't find any reference to 1/2/3 in 39783 item in globalEnergyObservatory
Where does it come from?
There are 5 units in Super-Bissorte pumping plant and 3 units in historical Bissorte plant.

It seems you miss Orelle power plant with 2 units also
https://www.openstreetmap.org/relation/2865506

**Comment by matteodefelice** [comment]
All the documents I could find are regarding Bissorte 1 and Super-bissorte (which is Bissorte 2 and 3). Also EDF considers Orelle as a separate plant wrt Bissorte and Super-bissorte: https://www.edf.fr/sites/default/files/Hydraulique/pays-de-savoie/documents/edf_hydraulique_alpes.pdf
In any case you are right, Orelle is missing but I am wondering if is associated to the Freney dam (Barrage de Freney) instead of Bissorte.

**Comment by flacombe** [comment]
> All the documents I could find are regarding Bissorte 1 and Super-bissorte (which is Bissorte 2 and 3)

That's right, and I understand then where does 1/2/3 come from, then.

>In any case you are right, Orelle is missing but I am wondering if is associated to the Freney dam (Barrage de Freney) instead of Bissorte.

Yes it does. Orelle is the single plant fed by Freney dam intake and is definitely run of river.
https://www.openstreetmap.org/relation/2865506
run-of-river is set on generators instead of plant : https://www.openstreetmap.org/node/2255728447
