### ISSUE TITLE
H1495 "Mella" with wrong geolocation or country code

### ISSUE THREAD

**Issue by timtroendle** [energy-modelling-toolkit/hydro-power-database#4]
Power plant H1495 with name "Mella" has Spain as its country code, but its geolocation points to Austria. I did a quick search online, but unfortunately did not find any traces of that plant and its actual location.

Version: 3

**Comment by matteodefelice** [comment]
Thanks for spotting this, I think this is one mistake propagated from one of the datasets we have used as inputs. In fact, at the same coordinates there is the Mellach hydro power plant in Austria, then I think that the H1495 can be removed without any problem.

**Comment by timtroendle** [comment]
I thought so too, and I am ignoring it in my analysis, but I wanted to report it anyways. Thanks!
