### ISSUE TITLE
Duplicate ids: H3287, H3299, H3282, H3286

### ISSUE THREAD

**Issue by timtroendle** [energy-modelling-toolkit/hydro-power-database#5]
The current release 04 contains four indices twice: H3287, H3299, H3282, H3286. The stations seem completely unrelated, as they are located in different countries.

**Comment by matteodefelice** [comment]
A new version of the database will be soon available with some issues fixed (like this one) and new additions. Thanks for reporting this mistake.

**Comment by matteodefelice** [comment]
Just published a new release, all the issues should be fixed.
