### ISSUE TITLE
Duplicate id

### ISSUE THREAD

**Issue by gperonato** [energy-modelling-toolkit/hydro-power-database#8]
There are currently some duplicate ids (e.g. H3371) in the database.
After cleaning, I would suggest adding [a unique constraint](https://specs.frictionlessdata.io/table-schema/#constraints) in the metadata.

**Comment by matteodefelice** [comment]
Thanks for spotting this, I will update the database soon. I will also add that constraint in the metadata.

**Comment by matteodefelice** [comment]
Dataset updated!
